language: rust

os:
  # - linux
  - osx

rust:
  - stable
  - beta
  - nightly
  - 1.26.0

script:
  - cargo test -- --test-threads=1 --nocapture
  - cargo test --release -- --test-threads=1 --nocapture
